from __future__ import annotations

from typing import Any, Protocol


class JiraServiceProtocol(Protocol):
    """Contract that both JiraService and DummyJiraService satisfy."""

    def find_epic_by_team(self, team_id: str) -> list[dict[str, Any]]: ...
    def create_epic(self, summary: str, description: str, team_id: str) -> dict[str, Any]: ...
    def update_epic(self, epic_key: str, fields: dict[str, Any]) -> dict[str, Any]: ...
    def create_story(
        self,
        epic_key: str,
        summary: str,
        description: str,
        acceptance_criteria: list[str],
        team_id: str,
    ) -> dict[str, Any]: ...
    def create_task(self, story_key: str, summary: str, description: str) -> dict[str, Any]: ...
    def get_epic(self, epic_key: str) -> dict[str, Any] | None: ...
    def get_story(self, story_key: str) -> dict[str, Any] | None: ...
    def get_subtasks(self, story_key: str) -> list[dict[str, Any]]: ...
    def update_story_description(self, story_key: str, description: str) -> None: ...
    def update_story_summary(self, story_key: str, summary: str) -> None: ...
    def transition_issue(self, issue_key: str, transition_name: str) -> None: ...
    def add_comment(self, issue_key: str, body: str) -> str | None: ...
    def update_comment(self, issue_key: str, comment_id: str, body: str) -> None: ...


class SlackServiceProtocol(Protocol):
    """Contract for Slack notification services."""

    def post_message(
        self, text: str, blocks: list[dict[str, Any]] | None = None,
    ) -> str | None: ...
    def update_message(
        self, ts: str, text: str, blocks: list[dict[str, Any]] | None = None,
    ) -> None: ...
    def post_thread_reply(self, thread_ts: str, text: str) -> None: ...


class GitHubServiceProtocol(Protocol):
    """Contract that both GitHubService and DummyGitHubService satisfy."""

    def pr_exists(self, branch_name: str) -> str | None: ...
    def create_pr(
        self,
        title: str,
        body: str,
        head_branch: str,
        base_branch: str | None = None,
        draft: bool = False,
    ) -> str: ...
