from __future__ import annotations

from typing import Any, Protocol


class JiraServiceProtocol(Protocol):
    """Contract that both JiraService and DummyJiraService satisfy."""

    def find_epic_by_team(self, team_id: str) -> list[dict[str, Any]]: ...
    def create_epic(self, summary: str, description: str, team_id: str) -> dict[str, Any]: ...
    def update_epic(self, epic_key: str, fields: dict[str, Any]) -> dict[str, Any]: ...
    def create_story(
        self,
        epic_key: str,
        summary: str,
        description: str,
        acceptance_criteria: list[str],
        team_id: str,
        *,
        extra_fields: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def get_epic_customfield_10112_value(self, epic_key: str) -> Any | None: ...
    def create_task(self, story_key: str, summary: str, description: str) -> dict[str, Any]: ...
    def get_epic(self, epic_key: str) -> dict[str, Any] | None: ...
    def get_story(self, story_key: str) -> dict[str, Any] | None: ...
    def list_stories_under_epic(self, epic_key: str) -> list[dict[str, Any]]: ...
    def get_subtasks(self, story_key: str) -> list[dict[str, Any]]: ...
    def update_story_description(self, story_key: str, description: str) -> None: ...
    def update_story_summary(self, story_key: str, summary: str) -> None: ...
    def transition_issue(self, issue_key: str, transition_name: str) -> None: ...
    def add_comment(self, issue_key: str, body: str) -> str | None: ...
    def update_comment(self, issue_key: str, comment_id: str, body: str) -> None: ...
    def set_story_branch_field(self, story_key: str, branch: str) -> None: ...
    def story_checklist_text_is_empty(self, story_key: str) -> bool: ...
    def set_story_checklist_text(self, story_key: str, markdown: str) -> None: ...


class SlackServiceProtocol(Protocol):
    """Contract for Slack notification services."""

    def post_message(
        self, text: str, blocks: list[dict[str, Any]] | None = None,
    ) -> str | None: ...
    def update_message(
        self, ts: str, text: str, blocks: list[dict[str, Any]] | None = None,
    ) -> None: ...
    def post_thread_reply(
        self, thread_ts: str, text: str, blocks: list[dict[str, Any]] | None = None,
    ) -> None: ...


class GitHubServiceProtocol(Protocol):
    """Contract that both GitHubService and DummyGitHubService satisfy."""

    def pr_exists(self, branch_name: str) -> str | None: ...
    def create_pr(
        self,
        title: str,
        body: str,
        head_branch: str,
        base_branch: str | None = None,
        draft: bool = False,
    ) -> str: ...
    def create_issue(
        self,
        title: str,
        body: str,
        labels: list[str] | None = None,
    ) -> tuple[str, int]: ...
    def get_issue(self, issue_number: int) -> dict[str, Any]: ...
    def add_issue_comment(self, issue_number: int, body: str) -> None: ...
    def close_issue(self, issue_number: int) -> None: ...
    def dispatch_workflow(
        self,
        workflow: str,
        inputs: dict[str, str],
        repo: str | None = None,
    ) -> None: ...
