from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from bmad_orchestrator.config import Settings
from bmad_orchestrator.services.protocols import GitHubServiceProtocol
from bmad_orchestrator.state import OrchestratorState
from bmad_orchestrator.utils.logger import get_logger

logger = get_logger(__name__)

NODE_NAME = "create_pull_request"

_PR_BODY_TEMPLATE = """\
## Story
**{story_id}**: {story_summary}

## Acceptance Criteria
{acceptance_criteria}

## Implementation Details
{implementation_details}

## Files Changed
{files_changed}

## QA Additions
{qa_summary}

## Code Review Resolution
{review_summary}

---
*Generated by BMAD Autonomous Engineering Orchestrator* 🤖
"""


_SKIP_DIRS = frozenset({
    "node_modules", ".git", "dist", "build", "__pycache__", ".venv", "venv", ".mypy_cache",
})


def _build_failure_section(
    state: OrchestratorState,
    settings: Settings,
) -> str:
    """Build a failure/diagnostic section prepended to the PR body when the pipeline failed."""
    failure_state = state.get("failure_state") or ""
    diagnostic = state.get("failure_diagnostic") or ""
    issues = state["code_review_issues"]

    lines: list[str] = []
    lines.append("## ⚠️ Pipeline Failed\n")
    lines.append(f"**Reason:** {failure_state}\n")

    if issues:
        lines.append("### Unresolved Issues")
        for issue in issues[:10]:
            sev = issue["severity"].upper()
            desc = issue["description"][:200]
            lines.append(f"- **[{sev}]** `{issue['file']}`: {desc}")
        lines.append("")

    test_output = state.get("test_failure_output") or ""
    if test_output:
        trimmed = test_output[:1500]
        if len(test_output) > 1500:
            trimmed += "\n… (truncated)"
        lines.append("### Test Failures")
        lines.append(f"```\n{trimmed}\n```\n")

    if diagnostic:
        lines.append("### Diagnostic")
        lines.append(diagnostic)
        lines.append("")

    # Resumption instructions with /bmad retry + gh CLI fallback
    branch = state.get("branch_name") or ""
    story_id = state.get("current_story_id") or ""
    target_repo = settings.github_repo or ""
    team_id = state["team_id"]
    prompt = state["input_prompt"].replace('"', '\\"')

    lines.append("### How to Continue")
    lines.append("")
    lines.append("**Option 1:** Comment on this PR:")
    lines.append("`/bmad retry Your guidance here`")
    lines.append("")
    lines.append("**Option 2:** Manual dispatch:")
    lines.append("```")

    extra = f"--story-key {story_id} --retry" if story_id else "--retry"
    lines.append(
        f"gh workflow run bmad-start-run.yml \\\n"
        f'  -f target_repo="{target_repo}" \\\n'
        f'  -f branch="{branch}" \\\n'
        f'  -f prompt="{prompt[:100]}" \\\n'
        f'  -f team_id="{team_id}" \\\n'
        f"  -f skip_check_epic_state=true \\\n"
        f"  -f skip_create_or_correct_epic=true \\\n"
        f"  -f skip_create_story_tasks=true \\\n"
        f"  -f skip_party_mode_refinement=true \\\n"
        f'  -f extra_flags="{extra}"'
    )
    lines.append("```")
    lines.append("")
    lines.append("---\n")

    return "\n".join(lines)


def _build_pr_body(state: OrchestratorState, settings: Settings) -> str:
    story_id = state["current_story_id"] or "UNKNOWN"
    story_content = state["story_content"] or state["input_prompt"]
    story_summary = story_content.splitlines()[0] if story_content else state["input_prompt"]

    ac_lines = "\n".join(
        f"- {ac}" for ac in (state["acceptance_criteria"] or [])
    ) or "- See Jira story for details"

    # Implementation details from developer + architect outputs
    details_parts: list[str] = []
    if state["architect_output"]:
        details_parts.append(
            f"### Architecture\n{state['architect_output'][:600]}"
        )
    if state["developer_output"]:
        details_parts.append(
            f"### Developer Notes\n{state['developer_output'][:600]}"
        )
    if not details_parts:
        details_parts.append(f"Implements: {state['input_prompt'][:200]}")
    implementation_details = "\n\n".join(details_parts)

    # Files changed (cap at 50 to keep body within GitHub's 65 536-char limit)
    artifact_files = sorted(
        {f for f in (state.get("touched_files") or [])
        if not any(part in _SKIP_DIRS for part in Path(f).parts)}
    )
    _MAX_FILES = 50
    if artifact_files:
        shown = artifact_files[:_MAX_FILES]
        rest = len(artifact_files) - len(shown)
        files_changed = "\n".join(f"- `{f}`" for f in shown)
        if rest:
            files_changed += f"\n- *…and {rest} more file(s)*"
    else:
        files_changed = "- See commit diff"

    qa_results = state["qa_results"]
    qa_summary = (
        "\n".join(
            f"- `{r['test_file']}`: {'✅ passed' if r['passed'] else '❌ failed'}"
            for r in qa_results
        )
        or "- No QA results recorded"
    )

    issues = state["code_review_issues"]
    if state.get("failure_state"):
        review_summary = (
            f"Pipeline failed with {len(issues)} unresolved issue(s) after "
            f"{state['review_loop_count']} review loop(s)."
        )
    elif issues:
        review_summary = (
            f"All {len(issues)} identified issue(s) resolved over "
            f"{state['review_loop_count']} review loop(s)."
        )
    else:
        review_summary = "No code review issues found."

    # Prepend failure section if pipeline failed
    failure_prefix = ""
    if state.get("failure_state"):
        failure_prefix = _build_failure_section(state, settings)

    body = failure_prefix + _PR_BODY_TEMPLATE.format(
        story_id=story_id,
        story_summary=story_summary[:120],
        acceptance_criteria=ac_lines,
        implementation_details=implementation_details,
        files_changed=files_changed,
        qa_summary=qa_summary,
        review_summary=review_summary,
    )
    # Hidden metadata for the /bmad retry workflow to parse
    target_repo = settings.github_repo or ""
    prompt_safe = state["input_prompt"].replace("-->", "")[:200]
    body += (
        f"\n<!-- bmad:target_repo={target_repo} -->"
        f"\n<!-- bmad:prompt={prompt_safe} -->"
        f"\n<!-- bmad:team_id={state['team_id']} -->"
    )

    # GitHub hard limit is 65 536 chars; truncate with a note rather than fail.
    _GITHUB_BODY_LIMIT = 65_000
    if len(body) > _GITHUB_BODY_LIMIT:
        body = (
            body[:_GITHUB_BODY_LIMIT]
            + "\n\n*[PR body truncated — see commit diff]*"
        )
    return body


def make_create_pull_request_node(
    github: GitHubServiceProtocol,
    settings: Settings,
) -> Callable[[OrchestratorState], dict[str, Any]]:

    def create_pull_request(state: OrchestratorState) -> dict[str, Any]:
        now = datetime.now(UTC).isoformat()

        # Idempotency: skip if PR already exists
        if state["pr_url"]:
            return {
                "pr_url": state["pr_url"],
                "execution_log": [{
                    "timestamp": now,
                    "node": NODE_NAME,
                    "message": f"PR already exists: {state['pr_url']}",
                    "dry_run": settings.dry_run,
                }],
            }

        # Guard: if commit_and_push found no changes, skip PR creation
        if not state["commit_sha"]:
            logger.warning("skip_pr_no_commit")
            return {
                "pr_url": None,
                "execution_log": [{
                    "timestamp": now,
                    "node": NODE_NAME,
                    "message": "No commit was made — skipping PR creation",
                    "dry_run": settings.dry_run,
                }],
            }

        branch_name = state["branch_name"] or ""
        existing = github.pr_exists(branch_name)
        if existing:
            return {
                "pr_url": existing,
                "execution_log": [{
                    "timestamp": now,
                    "node": NODE_NAME,
                    "message": f"PR already exists on GitHub: {existing}",
                    "dry_run": settings.dry_run,
                }],
            }

        story_id = state["current_story_id"] or "BMAD"
        input_prompt = state["input_prompt"]
        title = f"feat({state['team_id']}): {input_prompt[:60]} [{story_id}]"

        # Use the branch we were on before commit_and_push created the feature branch.
        # Falls back to settings.github_base_branch (default: "main") when not set.
        base = state["base_branch"] or settings.github_base_branch

        # Force draft when pipeline failed so the PR is clearly WIP
        is_draft = settings.draft_pr or bool(state.get("failure_state"))

        pr_url = github.create_pr(
            title=title,
            body=_build_pr_body(state, settings),
            head_branch=branch_name,
            base_branch=base,
            draft=is_draft,
        )

        return {
            "pr_url": pr_url,
            "execution_log": [{
                "timestamp": now,
                "node": NODE_NAME,
                "message": f"PR created: {pr_url}",
                "dry_run": settings.dry_run,
            }],
        }

    return create_pull_request
