from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from bmad_orchestrator.config import Settings
from bmad_orchestrator.services.protocols import GitHubServiceProtocol
from bmad_orchestrator.state import OrchestratorState
from bmad_orchestrator.utils.logger import get_logger

logger = get_logger(__name__)

NODE_NAME = "create_pull_request"

_PR_BODY_TEMPLATE = """\
## Story
**{story_id}**: {story_summary}

## Acceptance Criteria
{acceptance_criteria}

## Implementation Details
{implementation_details}

## Files Changed
{files_changed}

## QA Additions
{qa_summary}

## Code Review Resolution
{review_summary}

---
*Generated by BMAD Autonomous Engineering Orchestrator* 🤖
"""


_SKIP_DIRS = frozenset({
    "node_modules", ".git", "dist", "build", "__pycache__", ".venv", "venv", ".mypy_cache",
})


def _build_pr_body(state: OrchestratorState) -> str:
    story_id = state["current_story_id"] or "UNKNOWN"
    story_content = state["story_content"] or state["input_prompt"]
    story_summary = story_content.splitlines()[0] if story_content else state["input_prompt"]

    ac_lines = "\n".join(
        f"- {ac}" for ac in (state["acceptance_criteria"] or [])
    ) or "- See Jira story for details"

    # Implementation details from developer + architect outputs
    details_parts: list[str] = []
    if state["architect_output"]:
        details_parts.append(
            f"### Architecture\n{state['architect_output'][:600]}"
        )
    if state["developer_output"]:
        details_parts.append(
            f"### Developer Notes\n{state['developer_output'][:600]}"
        )
    if not details_parts:
        details_parts.append(f"Implements: {state['input_prompt'][:200]}")
    implementation_details = "\n\n".join(details_parts)

    # Files changed (cap at 50 to keep body within GitHub's 65 536-char limit)
    artifact_files = sorted(
        {f for f in (state.get("touched_files") or [])
        if not any(part in _SKIP_DIRS for part in Path(f).parts)}
    )
    _MAX_FILES = 50
    if artifact_files:
        shown = artifact_files[:_MAX_FILES]
        rest = len(artifact_files) - len(shown)
        files_changed = "\n".join(f"- `{f}`" for f in shown)
        if rest:
            files_changed += f"\n- *…and {rest} more file(s)*"
    else:
        files_changed = "- See commit diff"

    qa_results = state["qa_results"]
    qa_summary = (
        "\n".join(
            f"- `{r['test_file']}`: {'✅ passed' if r['passed'] else '❌ failed'}"
            for r in qa_results
        )
        or "- No QA results recorded"
    )

    issues = state["code_review_issues"]
    if issues:
        review_summary = (
            f"All {len(issues)} identified issue(s) resolved over "
            f"{state['review_loop_count']} review loop(s)."
        )
    else:
        review_summary = "No code review issues found."

    body = _PR_BODY_TEMPLATE.format(
        story_id=story_id,
        story_summary=story_summary[:120],
        acceptance_criteria=ac_lines,
        implementation_details=implementation_details,
        files_changed=files_changed,
        qa_summary=qa_summary,
        review_summary=review_summary,
    )
    # GitHub hard limit is 65 536 chars; truncate with a note rather than fail.
    _GITHUB_BODY_LIMIT = 65_000
    if len(body) > _GITHUB_BODY_LIMIT:
        body = (
            body[:_GITHUB_BODY_LIMIT]
            + "\n\n*[PR body truncated — see commit diff]*"
        )
    return body


def make_create_pull_request_node(
    github: GitHubServiceProtocol,
    settings: Settings,
) -> Callable[[OrchestratorState], dict[str, Any]]:

    def create_pull_request(state: OrchestratorState) -> dict[str, Any]:
        now = datetime.now(UTC).isoformat()

        # Idempotency: skip if PR already exists
        if state["pr_url"]:
            return {
                "pr_url": state["pr_url"],
                "execution_log": [{
                    "timestamp": now,
                    "node": NODE_NAME,
                    "message": f"PR already exists: {state['pr_url']}",
                    "dry_run": settings.dry_run,
                }],
            }

        branch_name = state["branch_name"] or ""
        existing = github.pr_exists(branch_name)
        if existing:
            return {
                "pr_url": existing,
                "execution_log": [{
                    "timestamp": now,
                    "node": NODE_NAME,
                    "message": f"PR already exists on GitHub: {existing}",
                    "dry_run": settings.dry_run,
                }],
            }

        story_id = state["current_story_id"] or "BMAD"
        input_prompt = state["input_prompt"]
        title = f"feat({state['team_id']}): {input_prompt[:60]} [{story_id}]"

        # Use the branch we were on before commit_and_push created the feature branch.
        # Falls back to settings.github_base_branch (default: "main") when not set.
        base = state["base_branch"] or settings.github_base_branch

        pr_url = github.create_pr(
            title=title,
            body=_build_pr_body(state),
            head_branch=branch_name,
            base_branch=base,
            draft=settings.draft_pr,
        )

        return {
            "pr_url": pr_url,
            "execution_log": [{
                "timestamp": now,
                "node": NODE_NAME,
                "message": f"PR created: {pr_url}",
                "dry_run": settings.dry_run,
            }],
        }

    return create_pull_request
